[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
smart_dial = "423KiBKFusrnh8QGcmj6rE9ntPWH7FzRQCJ5Z5kNeRmp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/git/miko_token/final-deployment/keypairs/deployer-keypair.json"

[workspace]
members = ["."]
