[programs.mainnet]
absolute_vault = "7eJ8NmvhSDcmqCP1HhSjuzvAacTWRqyFDjHoQXzHHghS"

[provider]
cluster = "mainnet"
wallet = "~/git/miko_token/final-deployment/keypairs/deployer-keypair.json"

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
